name: Wolk
favicon: null
layout_spectrum: 0.21774394949898124
typography_spectrum: 0.8664353510830551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.23669972619973123
  lightness: 0.3571918993256986
  saturation: 0.7747352181468159
  rhythmicContrast: 0.8230521865189075
purpose: []
